HEALTHFLOW_DWH.STAGINGUSE DATABASE HEALTHFLOW_DWH;
USE SCHEMA STAGING;

-- Patients
COPY INTO HEALTHFLOW_DWH.STAGING.STG_PATIENTS
FROM @S3_BRONZE_STAGE/patients/year=2026/month=01/day=05/
PATTERN = '.*\\.csv.*'
ON_ERROR = 'CONTINUE';

-- Admissions
COPY INTO HEALTHFLOW_DWH.STAGING.STG_ADMISSIONS
FROM @S3_BRONZE_STAGE/admissions/year=2026/month=01/day=05/
PATTERN = '.*\\.csv.*'
ON_ERROR = 'CONTINUE';

-- Services
COPY INTO HEALTHFLOW_DWH.STAGING.STG_SERVICES
FROM @S3_BRONZE_STAGE/services/year=2026/month=01/day=05/
PATTERN = '.*\\.csv.*'
ON_ERROR = 'CONTINUE';

-- Stocks médicaments 
COPY INTO HEALTHFLOW_DWH.STAGING.STG_STOCKS_MEDICAMENTS
FROM @S3_BRONZE_STAGE/stocks_medicaments/year=2026/month=01/day=05/
PATTERN = '.*\\.csv.*'
ON_ERROR = 'CONTINUE';
